services:
  operations-center:
    image: ${DOCKER_IMAGE_CJOC}
    platform: linux/amd64
    extra_hosts:
      - "${CJOC_URL}:${HAPROXY_IP}"
      - "${CONTROLLER_URL}:${HAPROXY_IP}"
    healthcheck:
      test: curl -k --fail ${HTTP_PROTOCOL}://localhost:${HTTP_PORT}/whoAmI/api/json?tree=authenticated || exit 1
      interval: 3s
      timeout: 3s
      retries: 50
    environment:
      - JAVA_OPTS=${CJOC_JAVA_OPTS}
      - JENKINS_OPTS=${CJOC_JENKINS_OPTS}
      - CJOC_LOGIN_PW=${CJOC_LOGIN_PW}
      - CJOC_LOGIN_USER=${CJOC_LOGIN_USER}
      - CJOC_URL=${HTTP_PROTOCOL}://${CJOC_URL}
      - CJOC_CASC_DEFAULT_BUNDLE=${CJOC_CASC_DEFAULT_BUNDLE}
    container_name: operations-center
    volumes:
      - ${CJOC_PERSISTENCE}:/var/jenkins_home
      - ${CJOC_CASC_BUNDLE_PATH_LOCAL}:${CASC_BUNDLE_PATH_CONTAINER}
      - ./ssl/cacerts:/tmp/cacerts
      # - ./ssl/jenkins.jks:/tmp/jenkins.jks
      # - ./ssl/jenkins.p12:/tmp/jenkins.p12
      # - ./ssl/cacerts:/tmp/cacerts
    networks:
      demo-network:
        ipv4_address: ${CJOC_IP}
  # Sidecar bunlde-link.yaml init doesent work yet, oc  hostname can not be resolved?
  #  init-controllers:
  #    image: curlimages/curl
  #    extra_hosts:
  #      - "${CJOC_URL}:${HAPROXY_IP}"
  #    command: ["/bin/sh", "-c", "set -x && curl -v -k -L --user '${CJOC_LOGIN_USER}:${CJOC_LOGIN_PW}' -XGET -o /var/jenkins_home/bundle-link.yaml '${HTTP_PROTOCOL}://operations-center:${HTTP_PORT}/config-bundle-download-link?id=ha' && cat /var/jenkins_home/bundle-link.yaml"]
  #    container_name: init-controllers
  #    healthcheck:
  #      test: test -f /var/jenkins_home/bundle-link.yaml
  #      interval: 5s
  #      timeout: 3s
  #      retries: 5
  #      start_period: 2s
  #    depends_on:
  #      operations-center:
  #        condition: service_healthy
  #    volumes:
  #      - ${CONTROLLER_PERSISTENCE}:/var/jenkins_home
  #    networks:
  #      demo-network:
  #        ipv4_address: ${INIT_CLIENT_IP}

  controller:
    image: ${DOCKER_IMAGE_CONTROLLER}
    platform: linux/amd64
    extra_hosts:
      - "${CJOC_URL}:${HAPROXY_IP}"
      - "${CONTROLLER_URL}:${HAPROXY_IP}"
    depends_on:
      operations-center:
        condition: service_healthy
    healthcheck:
      test: curl -k --fail ${HTTP_PROTOCOL}://localhost:${HTTP_PORT}/whoAmI/api/json?tree=authenticated || exit 1
      interval: 3s
      timeout: 3s
      retries: 150
    environment:
      - JAVA_OPTS=${CONTROLLER_JAVA_OPTS}
      - JENKINS_OPTS=${CONTROLLER_JENKINS_OPTS}
      - CONTROLLER_URL=${HTTP_PROTOCOL}://${CONTROLLER_URL}
    #    depends_on:
    #      init-controllers:
    #        condition: service_healthy
    # entrypoint: ["sh", "-c", "while [ ! -f /var/jenkins_home/bundle-link.yaml ]; do echo 'wait for bundle-link.yaml' && sleep 1; done;"]

    container_name: controller

    volumes:
      - ${CONTROLLER_PERSISTENCE}:/var/jenkins_home
      - ${CONTROLLER_CACHE}:/var/cache
      - ${CONTROLLER_CASC_BUNDLE_PATH_LOCAL}:${CASC_BUNDLE_PATH_CONTAINER}
      - ./ssl/cacerts:/tmp/cacerts
      # - ./ssl/jenkins.jks:/tmp/jenkins.jks
      # - ./ssl/jenkins.p12:/tmp/jenkins.p12


    networks:
      demo-network:
        ipv4_address: ${CONTROLLER_IP}
  haproxy:
    image: ${DOCKER_IMAGE_HAPROXY}
    volumes:
      - ${HA_PROXY_CONFIG}:/usr/local/etc/haproxy/haproxy.cfg
      - ${LOCAL_VOLUME}/haproxy:/etc/ssl/
      - ./ssl/jenkins.pem:/etc/ssl/certs/jenkins.pem
    ports:
      - "${HA_PROXY_BIND_PORT}:${HA_PROXY_BIND_PORT}"
    container_name: haproxy
    networks:
      demo-network:
        ipv4_address: ${HAPROXY_IP}
    # depends_on:
    #   controller:
    #     condition: service_healthy
    extra_hosts:
      - "${CJOC_URL}:${CJOC_IP}"
      - "${CONTROLLER_URL}:${CONTROLLER_IP}"
  # browser:
  #   image: ${DOCKER_IMAGE_BROWSER_BOX}
  #   container_name: webtop
  #   security_opt:
  #     - seccomp:unconfined #optional
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #     - SUBFOLDER=/ #optional
  #     - TITLE=Webtop #optional
  #   volumes:
  #     - ${BROWSER_PERSISTENCE}:/config
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   #devices:
  #   #  - /dev/dri:/dev/dri #optional
  #   shm_size: "2gb" #optional
  #   restart: unless-stopped
  #   extra_hosts:
  #     - "${CJOC_URL}:${HAPROXY_IP}"
  #     - "${CONTROLLER_URL}:${HAPROXY_IP}"
  #   networks:
  #     demo-network:
  #       ipv4_address: ${BROWSER_IP}

networks:
  demo-network:
    driver: bridge
    #driver_opts:
    #  com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
    ipam:
      config:
        - subnet: ${IP_PREFIX}.0.0/24
